import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import HomePage from "@/components/home";
import HomeGenerateBox from "@/components/homeGenerateBox";
import { HomeBlackBox } from "@/components/homeBlackBox";
import HomeFaqSection from "@/components/homeFaqSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>
        <Navbar/>
        <HomePage/>
        <HomeGenerateBox/>
        <HomeBlackBox/><br></br>
        <HomeFaqSection/>
        <Footer/>
    </div>
    </>
  );
}
